plugin: google.cloud.gcp_compute
projects:
  - cluster-lab-2
service_account_file: ../service_account.json
auth_kind: serviceaccount
scopes:
  - 'https://www.googleapis.com/auth/cloud-platform'
  - 'https://www.googleapis.com/auth/compute.readonly'
groups:
  # all machines created in gcp are dev machines
  dev: 'True'
hostnames:
  - name
compose:
  ansible_user: root
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_ssh_private_key_file: ../ssh/google_compute_engine
  ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
