[project]
name = "cluster-lab"
version = "0.1.0"
description = "experiments with cluster creation/management"
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.1.0",
    "google-auth>=1.3.0",
    "requests>=2.18.4",
]
